# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20170727_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='static/posts/images/default.jpg', upload_to='static/posts/images/user_pics/'),
        ),
    ]
