# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170815_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')]),
        ),
    ]
